%:
	javac -d ../../out -classpath './;./src/Terrain;../../libs/core.jar;./lib;../../libs/gluegen-rt.jar;../../libs/jogl-all.jar;../../libs/joml-1.10.5.jar' '$@.java' 
	java -classpath '../../out;../../libs/*' $@